# Site settings
title: Junteng Liu
name: Junteng Liu
description: First-year PhD candidate at HKUST NLP Group. Research in Natural Language Processing and Machine Learning.
baseurl: ""
url: "https://LLLeoLi.github.io/LJT-Homepage"
twitter_username: junteng88716710
github_username: Vicent0205
email: jliugi@connect.ust.hk

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: false
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: false
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: false

# Site Author
author:
  name   : "Junteng Liu"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "First-year PhD candidate at HKUST NLP Group"
  location : "Hong Kong"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jliugi@connect.ust.hk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"

# Reading Files
include:
  - _pages

# Outputting
permalink: /:categories/:title/
timezone: Asia/Hong_Kong

# Markdown Processing
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 2..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Sass/SCSS
sass:
  style: compressed

# Feed
feed:
  categories: false
  path: atom.xml

# SEO
seo:
  type: Person
  name: Junteng Liu
  links:
    - https://github.com/Vicent0205
    - https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate
    - https://twitter.com/junteng88716710

# Comments
comments:
  provider: false

# Search
search: true

# Pagination
paginate: 5
paginate_path: /page:num/

# Misc
repository: LLeoLi/LJT-Homepage

# Social sharing
social:
  type: Person
  name: Junteng Liu
  links:
    - https://github.com/Vicent0205
    - https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate
    - https://twitter.com/junteng88716710

# UI Text
ui_text:
  related_posts: "You may also enjoy"
  read_more: "Read more"
  read_time: " min read"
  words_per_minute: 200

# Sort definitions
publications_sort: date
talks_sort: date
portfolio_sort: date
teaching_sort: date

# Date format
date_format: "%B %-d, %Y"

# Icons
icon:
  rss: true

# Sitemap
sitemap: true

# Back to top button
back_to_top: true